### PR TITLE
Some bug fixes found while preparing the NAB presentation

### PR DESCRIPTION
**Pull request by lordross**
1. Fix handling of files larger than  4 GB
2. Fix parameters passed to get/put operations

### CODE REVIEW

**Comment by rpmoore** [comment]
It does not look like you've signed our Contributor Agreement.  Before we can accept the pull request you must first go to https://developer.spectralogic.com/contributors-agreement/ and sign the agreement.

Thanks for the pull request!

**Comment by lordross** [comment]
I am working for Tiger Technology OOD and I am almost sure my colleagues already signed this a couple of months before probably by tigertechdev github account. Can you check, please? Or just to sign it again with this account?

**Comment by rpmoore** [comment]
Please sign it with this account.

**Comment by lordross** [comment]
OK. I have signed it.

**Comment by rpmoore** [comment]
Thank!  I just got the notification for it.

**Pull request merged**
