### PR TITLE
fixed bug in head_object and delete_object when an empty bucket name is passed

### PR DESCRIPTION
**Pull request by chanchett**
…ssed

### CODE REVIEW

**Comment by rpmoore** [comment]
Before this is merged I want to find out from Jason how this change will affect folders.  In Spectra S3 we will create folders if you ask for them to be created.  We should see before this is merged what exactly should happen.

**Comment by chanchett** [comment]
That makes total sense. I worried a little bit about that implementing it this way.

**Comment by rpmoore** [comment]
So what was the answer on this?

**Comment by chanchett** [comment]
Jason said he couldn't see any way it would be a problem.

**Pull request merged**
